# Generated by Django 4.2.20 on 2025-05-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_alter_category_options_alter_icecream_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='wrapper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ice_creams', to='ice_cream.wrapper', verbose_name='Обёртка'),
        ),
    ]
